# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('firmware_flash', '0001_initial'), ('firmware_flash', '0002_flashrequest'), ('firmware_flash', '0003_multipart'), ('firmware_flash', '0004_update_firmware_models')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the board', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='The description of the board')),
                ('weight', models.IntegerField(choices=[(1, '1 (Highest)'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9  (Lowest)')], default=5, help_text='Weight for sorting (Lower weights rise to the top)')),
                ('flash_options_json', models.TextField(blank=True, default='', help_text='A JSON list containing options to pass to subprocess')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='DeviceFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the device family', max_length=30)),
                ('flash_method', models.CharField(choices=[('avrdude', 'Avrdude (Arduino)'), ('esptool', 'Esptool (ESP8266)')], default='avrdude', max_length=30)),
                ('detection_family', models.CharField(choices=[('arduino', 'Arduino'), ('esp8266', 'ESP8266'), ('particle', 'Particle (Spark/Core)')], default='arduino', max_length=30)),
            ],
            options={
                'verbose_name': 'Device Family',
                'verbose_name_plural': 'Device Families',
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the firmware', max_length=128)),
                ('version', models.CharField(default='0.0', help_text='The major version number', max_length=20)),
                ('revision', models.CharField(default='0.0', help_text='The minor revision number', max_length=20)),
                ('variant', models.CharField(blank=True, default='', help_text="The firmware 'variant' (if applicable)", max_length=80)),
                ('is_fermentrack_supported', models.BooleanField(default=False, help_text='Is this firmware officially supported by Fermentrack?')),
                ('in_error', models.BooleanField(default=False, help_text='Is there an error with this firmware that should prevent it from being downloaded?')),
                ('description', models.TextField(blank=True, default='', help_text='The description of the firmware')),
                ('variant_description', models.TextField(blank=True, default='', help_text='The description of the variant')),
                ('post_install_instructions', models.TextField(blank=True, default='', help_text='Instructions to be displayed to the user after installation')),
                ('download_url', models.CharField(blank=True, default='', help_text='The URL at which the firmware can be downloaded', max_length=255)),
                ('project_url', models.CharField(blank=True, default='', help_text='The URL for the project associated with the firmware', max_length=255)),
                ('documentation_url', models.CharField(blank=True, default='', help_text='The URL for documentation/help on the firmware (if any)', max_length=255)),
                ('weight', models.IntegerField(choices=[(1, '1 (Highest)'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9  (Lowest)')], default=5, help_text='Weight for sorting (Lower weights rise to the top)')),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA256 checksum of the file (for checking validity)', max_length=64)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.DeviceFamily')),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmware',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.DeviceFamily'),
        ),
        migrations.CreateModel(
            name='FlashRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=32)),
                ('serial_port', models.CharField(help_text='Path to the serial device used with the flash tool', max_length=255)),
                ('result_text', models.CharField(blank=True, default=None, help_text='String explaining the result status', max_length=255, null=True)),
                ('flash_output', models.TextField(blank=True, default=None, help_text='Output from the flash tool', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date this flash request was created')),
                ('board_type', models.ForeignKey(help_text='Board type being flashed', on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.Board')),
                ('firmware_to_flash', models.ForeignKey(help_text='Firmware to flash', on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.Firmware')),
            ],
        ),
        migrations.AddField(
            model_name='firmware',
            name='checksum_partitions',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the partitions file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='checksum_spiffs',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the SPIFFS file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_partitions',
            field=models.CharField(blank=True, default='', help_text='The URL at which the partitions binary can be downloaded (ESP32 only, optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_spiffs',
            field=models.CharField(blank=True, default='', help_text='The URL at which the SPIFFS binary can be downloaded (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='spiffs_address',
            field=models.CharField(blank=True, default='', help_text='The flash address the SPIFFS data should be flashed to', max_length=12),
        ),
        migrations.AlterField(
            model_name='devicefamily',
            name='detection_family',
            field=models.CharField(choices=[('arduino', 'Arduino'), ('esp8266', 'ESP8266'), ('particle', 'Particle (Spark/Core)'), ('esp32', 'ESP32')], default='arduino', max_length=30),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project the firmware is associated with', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='The description of the project')),
                ('project_url', models.CharField(blank=True, default='', help_text='The URL for the project associated with the firmware', max_length=255)),
                ('documentation_url', models.CharField(blank=True, default='', help_text='The URL for documentation/help on the firmware (if any)', max_length=255)),
                ('support_url', models.CharField(blank=True, default='', help_text='The URL for support (if any, generally a forum thread)', max_length=255)),
                ('weight', models.IntegerField(choices=[(1, '1 (Highest)'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9  (Lowest)')], default=5, help_text='Weight for sorting (Lower weights rise to the top)')),
                ('show_in_standalone_flasher', models.BooleanField(default=False, help_text='Should this show standalone flash app?')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='project_url',
        ),
        migrations.AddField(
            model_name='firmware',
            name='checksum_bootloader',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the bootloader file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='checksum_otadata',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the otadata file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_bootloader',
            field=models.CharField(blank=True, default='', help_text='The URL at which the bootloader binary can be downloaded (ESP32 only, optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_otadata',
            field=models.CharField(blank=True, default='', help_text='The URL at which the OTA Dta binary can be downloaded (ESP32 only, optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='otadata_address',
            field=models.CharField(blank=True, default='', help_text='The flash address the SPIFFS data should be flashed to (ESP32 only)', max_length=12),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='revision',
            field=models.CharField(blank=True, default='', help_text='The minor revision number', max_length=20),
        ),
        migrations.AddField(
            model_name='firmware',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firmware_flash.Project'),
        ),
    ]
