# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=32)),
                ('serial_port', models.CharField(help_text='Path to the serial device used with the flash tool', max_length=255)),
                ('result_text', models.CharField(blank=True, default=None, help_text='String explaining the result status', max_length=255, null=True)),
                ('flash_output', models.TextField(blank=True, default=None, help_text='Output from the flash tool', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date this flash request was created')),
                ('board_type', models.ForeignKey(help_text='Board type being flashed', on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.Board')),
                ('firmware_to_flash', models.ForeignKey(help_text='Firmware to flash', on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.Firmware')),
            ],
        ),
    ]
