# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-13 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0001_Initial Setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefamily',
            name='detection_family',
            field=models.CharField(choices=[('arduino', 'Arduino'), ('esp8266', 'ESP8266'), ('particle', 'Particle (Spark/Core)')], default='arduino', max_length=30),
        ),
    ]
