# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0002_flashrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='checksum_partitions',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the partitions file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='checksum_spiffs',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the SPIFFS file (for checking validity)', max_length=64),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_partitions',
            field=models.CharField(blank=True, default='', help_text='The URL at which the partitions binary can be downloaded (ESP32 only, optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='download_url_spiffs',
            field=models.CharField(blank=True, default='', help_text='The URL at which the SPIFFS binary can be downloaded (ESP32 only, optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='firmware',
            name='spiffs_address',
            field=models.CharField(blank=True, default='', help_text='The flash address the SPIFFS data is at (ESP32 only, optional)', max_length=12),
        ),
        migrations.AlterField(
            model_name='devicefamily',
            name='detection_family',
            field=models.CharField(choices=[('arduino', 'Arduino'), ('esp8266', 'ESP8266'), ('particle', 'Particle (Spark/Core)'), ('esp32', 'ESP32')], default='arduino', max_length=30),
        ),
    ]
