# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0002_Tweak DeviceFamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of the file (for checking validity)', max_length=64),
        ),
    ]
