# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0003_Add Checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the board', max_length=128)),
                ('description', models.TextField(blank=True, default='', help_text='The description of the board')),
                ('weight', models.IntegerField(choices=[(1, '1 (Highest)'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9  (Lowest)')], default=5, help_text='Weight for sorting (Lower weights rise to the top)')),
                ('flash_options_json', models.TextField(blank=True, default='', help_text='A JSON list containing options to pass to subprocess')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware_flash.DeviceFamily')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
    ]
