# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_flash', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='post_install_instructions',
            field=models.TextField(blank=True, default='', help_text='Instructions to be displayed to the user after installation'),
        ),
    ]
