# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0005_brewpidevice_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewpidevice',
            name='time_profile_started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
