# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0006_auto_20170205_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerlogpoint',
            options={'managed': False, 'ordering': ['log_time'], 'verbose_name': 'Beer Log Point', 'verbose_name_plural': 'Beer Log Points'},
        ),
        migrations.RemoveField(
            model_name='brewpidevice',
            name='process_id',
        ),
        migrations.AddField(
            model_name='beer',
            name='format',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
