# Generated by Django 3.0.6 on 2020-11-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0009_auto_20180709_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationprofile',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes about the fermentation profile (Optional)'),
        ),
    ]
