# Generated by Django 3.0.13 on 2021-04-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fermentationprofile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewpidevice',
            name='wifi_host_ip',
            field=models.CharField(blank=True, default='', help_text='Cached IP address in case of mDNS issues (only used if connection_type is wifi)', max_length=46),
        ),
    ]
