# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brewpidevice_time_profile_started'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallSettings',
        ),
        migrations.AlterModelOptions(
            name='brewpidevice',
            options={'verbose_name': 'BrewPi Device', 'verbose_name_plural': 'BrewPi Devices'},
        ),
        migrations.AlterModelOptions(
            name='sensordevice',
            options={'managed': False, 'verbose_name': 'Sensor Device', 'verbose_name_plural': 'Sensor Devices'},
        ),
    ]
