# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170212_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='model_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='oldcontrolconstants',
            name='hs',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'No')], default=0, help_text='If this option is set to yes, the rotary encoder will use half steps', verbose_name='Use half steps for rotary encoder?'),
        ),
        migrations.AlterField(
            model_name='oldcontrolconstants',
            name='lah',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'No')], default=0, help_text='If set to yes the chamber light (if assigned a pin) will be used in place of the heat pin', verbose_name='Using light as heater?'),
        ),
    ]
