# Generated by Django 3.2.12 on 2022-03-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_allow_blank_wifi_host_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewpidevice',
            name='status',
            field=models.CharField(choices=[('active', 'Active, Managed by Fermentrack'), ('unmanaged', 'Active, NOT managed by Fermentrack'), ('disabled', 'Explicitly disabled, cannot be launched'), ('updating', 'Disabled, pending an update')], default='active', max_length=15),
        ),
    ]
