# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prep for serial udev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewpidevice',
            name='udev_serial_number',
            field=models.CharField(blank=True, default='', help_text='USB Serial ID number for autodetection of serial port', max_length=255),
        ),
    ]
