# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170115_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewpidevice',
            name='has_old_brewpi_www',
        ),
        migrations.RemoveField(
            model_name='brewpidevice',
            name='wwwPath',
        ),
        migrations.AddField(
            model_name='oldcontrolconstants',
            name='tempFormat',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
