# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_update udev to add blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationprofile',
            name='profile_type',
            field=models.CharField(default='Standard Profile', help_text='Type of temperature profile', max_length=32),
        ),
    ]
