# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_Add Profile Type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldcontrolconstants',
            name='tempFormat',
            field=models.CharField(choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], default='F', help_text='This is the temperature format that will be used by the device', max_length=1, verbose_name='Temperature format'),
        ),
    ]
