# Generated by Django 3.2.12 on 2023-06-17 17:35

from django.db import migrations, models
from app.models import Beer, BrewPiDevice, FermentationProfile
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_extended_settings'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Beer.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in BrewPiDevice.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in FermentationProfile.objects.all():
            row.uuid = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='beer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this beer log'),
        ),
        migrations.AddField(
            model_name='brewpidevice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this temperature controller'),
        ),
        migrations.AddField(
            model_name='fermentationprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this profile'),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='beer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this beer log', unique=True),
        ),
        migrations.AlterField(
            model_name='brewpidevice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this temperature controller',
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='fermentationprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this profile', unique=True),
        ),

    ]
