# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171105_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewpidevice',
            name='active_beer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Beer'),
        ),
        migrations.AlterField(
            model_name='brewpidevice',
            name='active_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.FermentationProfile'),
        ),
    ]
