# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180429_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='model_version',
            field=models.IntegerField(default=2, help_text='Version # used for the logged file format'),
        ),
    ]
