# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180709_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/generic_logo.png', null=True, upload_to='beer_profile/'),
        ),
    ]
