# Generated by Django 3.0.6 on 2020-05-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fermentationprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentationprofile',
            name='image',
        ),
    ]
