# Generated by Django 3.0.6 on 2020-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_fermentationprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentationprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beer_profile/'),
        ),
    ]
