# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpushtarget',
            name='brewpi_to_push',
            field=models.ManyToManyField(blank=True, default=None, help_text="BrewPi Devices to push (ignored if 'all' devices selected)", related_name='push_targets', to='app.BrewPiDevice'),
        ),
        migrations.AlterField(
            model_name='genericpushtarget',
            name='gravity_sensors_to_push',
            field=models.ManyToManyField(blank=True, default=None, help_text="Gravity Sensors to push (ignored if 'all' sensors selected)", related_name='push_targets', to='gravity.GravitySensor'),
        ),
        migrations.AlterField(
            model_name='genericpushtarget',
            name='last_triggered',
            field=models.DateTimeField(auto_now_add=True, help_text='The last time we pushed data to this target'),
        ),
    ]
