# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0004_BrewersFriend_Support'),
        ('external_push', '0002_auto_20190220_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewersFriendPushTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', help_text='Status of this push target', max_length=24)),
                ('push_frequency', models.IntegerField(choices=[(59, '1 minute'), (119, '2 minutes'), (299, '5 minutes'), (599, '10 minutes'), (899, '15 minutes'), (1799, '30 minutes'), (3599, '1 hour')], default=900, help_text='How often to push data to the target')),
                ('api_key', models.CharField(default='', help_text='Brewers Friend API Key', max_length=256)),
                ('error_text', models.TextField(blank=True, default='', help_text='The error (if any) encountered on the last push attempt', null=True)),
                ('last_triggered', models.DateTimeField(auto_now_add=True, help_text='The last time we pushed data to this target')),
                ('gravity_sensor_to_push', models.ForeignKey(help_text='Gravity Sensor to push (create one push target per sensor to push)', on_delete=django.db.models.deletion.CASCADE, related_name='push_target', to='gravity.GravitySensor')),
            ],
            options={
                'verbose_name': 'Brewers Friend Push Target',
                'verbose_name_plural': 'Brewers Friend Push Targets',
            },
        ),
        migrations.AddField(
            model_name='genericpushtarget',
            name='error_text',
            field=models.TextField(blank=True, default='', help_text='The error (if any) encountered on the last push attempt', null=True),
        ),
        migrations.AlterField(
            model_name='genericpushtarget',
            name='data_format',
            field=models.CharField(choices=[('generic', 'All Data (Generic)')], default='generic', help_text='The data format to send to the push target', max_length=24),
        ),
        migrations.AlterField(
            model_name='genericpushtarget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', help_text='Status of this push target', max_length=24),
        ),
    ]
