# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0004_BrewersFriend_Support'),
        ('external_push', '0005_ThingSpeak_Support'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainfatherPushTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='active', help_text='Status of this push target', max_length=24)),
                ('push_frequency', models.IntegerField(choices=[(901, '15 minutes'), (1801, '30 minutes'), (3601, '1 hour')], default=900, help_text='How often to push data to the target')),
                ('logging_url', models.CharField(default='', help_text='Grainfather Logging URL', max_length=256)),
                ('gf_name', models.CharField(default='', help_text='Grainfather brew id (number)', max_length=256)),
                ('error_text', models.TextField(blank=True, default='', help_text='The error (if any) encountered on the last push attempt', null=True)),
                ('last_triggered', models.DateTimeField(auto_now_add=True, help_text='The last time we pushed data to this target')),
                ('gravity_sensor_to_push', models.ForeignKey(help_text='Gravity Sensor to push (create one push target per sensor to push)', on_delete=django.db.models.deletion.CASCADE, related_name='grainfather_push_target', to='gravity.GravitySensor')),
            ],
            options={
                'verbose_name': 'Grainfather Push Target',
                'verbose_name_plural': 'Grainfather Push Targets',
            },
        ),
    ]
