# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180709_0256'),
        ('external_push', '0006_Grainfather_Support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingspeakpushtarget',
            name='brewpi_to_push_id',
        ),
        migrations.AddField(
            model_name='thingspeakpushtarget',
            name='brewpi_to_push',
            field=models.ForeignKey(blank=True, default=None, help_text="BrewPi Devices to push (ignored if 'all' devices selected)", on_delete=django.db.models.deletion.CASCADE, related_name='thingspeak_push_targets', to='app.BrewPiDevice'),
        ),
        migrations.AlterField(
            model_name='thingspeakpushtarget',
            name='api_key',
            field=models.CharField(default='', help_text='ThingSpeak Channel API Key', max_length=256),
        ),
        migrations.AlterField(
            model_name='thingspeakpushtarget',
            name='push_frequency',
            field=models.IntegerField(choices=[(59, '1 minute'), (119, '2 minutes'), (299, '5 minutes'), (599, '10 minutes'), (899, '15 minutes'), (1799, '30 minutes'), (3599, '1 hour')], default=900, help_text='How often to push data to the target'),
        ),
    ]
