# Generated by Django 3.1.7 on 2021-04-22 14:51

from django.db import migrations, models
import django.utils.timezone
import backups.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('filename_prefix', models.CharField(default=backups.models.default_filename_prefix, help_text="The filename prefix for this backup's archive", max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
