# Generated by Django 3.1.8 on 2021-04-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'permissions': [('restore_backup', 'Can restore from a backup (which can overwrite all data in Fermentrack)')]},
        ),
    ]
