#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /app
# TODO - Figure out logging here
python -u manage.py run_huey


#[watcher:huey]
#cmd = python
#args = manage.py run_huey
#working_dir = /app
#copy_env = True
##copy_path = True
#
#use_sockets = False
#numprocesses = 1
## Log output, rotate every 2MB, keep 3 logfiles.
#stderr_stream.class = FileStream
#stderr_stream.filename = log/huey-stderr.log
#stderr_stream.refresh_time = 0.3
#stderr_stream.max_bytes = 2097152
#stderr_stream.backup_count = 3
#
#stdout_stream.class = FileStream
#stdout_stream.filename = log/huey-stdout.log
#stdout_stream.refresh_time = 0.3
#stdout_stream.max_bytes = 2097152
#stdout_stream.backup_count = 3
#
#[env:huey]
#PYTHONPATH  = /app
