# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-23 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravitysensor',
            name='logging_status',
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='assigned_brewpi_device',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.BrewPiDevice'),
        ),
    ]
