# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiltConfiguration',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tilt_configuration', serialize=False, to='gravity.GravitySensor')),
                ('color', models.CharField(choices=[('black', 'Black'), ('orange', 'Orange'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('pink', 'Pink')], max_length=32)),
                ('average_period_secs', models.IntegerField(default=300)),
                ('median_window_vals', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TiltGravityCalibrationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Original (Sensor) Gravity Value')),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Actual (Measured) Gravity Value')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.TiltConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TiltTempCalibrationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Original (Sensor) Temp Value')),
                ('actual_value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Actual (Measured) Temp Value')),
                ('temp_format', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.TiltConfiguration')),
            ],
        ),
    ]
