# Generated by Django 3.0.5 on 2020-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_squashed_0005_auto_20200416_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiltgravitycalibrationpoint',
            name='actual_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Actual (Correct) Gravity value'),
        ),
        migrations.AlterField(
            model_name='tiltgravitycalibrationpoint',
            name='tilt_measured_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tilt Measured Gravity Value'),
        ),
    ]
