# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_auto_20171023_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravitysensor',
            name='readings_to_average',
            field=models.IntegerField(default=1, help_text='If using averaged readings, how many readings should be included in the average?'),
        ),
        migrations.AddField(
            model_name='gravitysensor',
            name='use_averaged_readings',
            field=models.BooleanField(default=False, help_text='Should this sensor use an average of the last X readings rather than just the last reading?'),
        ),
        migrations.AlterField(
            model_name='gravitylog',
            name='format',
            field=models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='active_log',
            field=models.ForeignKey(blank=True, default=None, help_text='The currently active log of readings', null=True, on_delete=django.db.models.deletion.CASCADE, to='gravity.GravityLog'),
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='assigned_brewpi_device',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravity_sensor', to='app.BrewPiDevice'),
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='status',
            field=models.CharField(choices=[('active', 'Active, Managed by Circus'), ('unmanaged', 'Active, NOT managed by Circus'), ('disabled', 'Explicitly disabled, cannot be launched'), ('updating', 'Disabled, pending an update')], default='active', help_text='Status of the gravity sensor (used by scripts that interact with it)', max_length=15),
        ),
    ]
