# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_tilt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IspindelConfiguration',
            fields=[
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ispindel_configuration', serialize=False, to='gravity.GravitySensor')),
                ('name_on_device', models.CharField(help_text='The name configured on the iSpindel device itself', max_length=64, unique=True)),
                ('third_degree_coefficient', models.DecimalField(decimal_places=10, default=0.0, help_text='The third degree coefficient in the gravity conversion equation', max_digits=13)),
                ('second_degree_coefficient', models.DecimalField(decimal_places=10, default=0.0, help_text='The second degree coefficient in the gravity conversion equation', max_digits=13)),
                ('first_degree_coefficient', models.DecimalField(decimal_places=10, default=0.0, help_text='The first degree coefficient in the gravity conversion equation', max_digits=13)),
                ('constant_term', models.DecimalField(decimal_places=10, default=0.0, help_text='The constant term in the gravity conversion equation', max_digits=13)),
                ('coefficients_up_to_date', models.BooleanField(default=False, help_text='Have the calibration points changed since the coefficient calculator was run?')),
            ],
        ),
        migrations.CreateModel(
            name='IspindelGravityCalibrationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Angle (Measured by Device)')),
                ('gravity', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Gravity Value (Measured Manually)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.IspindelConfiguration')),
            ],
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='sensor_type',
            field=models.CharField(choices=[('tilt', 'Tilt Hydrometer'), ('ispindel', 'iSpindel'), ('manual', 'Manual')], default='manual', help_text='Type of gravity sensor used', max_length=10),
        ),
    ]
