# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_tilt_refactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiltbridge',
            old_name='api_key',
            new_name='mdns_id',
        ),
        migrations.AlterField(
            model_name='tiltbridge',
            name='mdns_id',
            field=models.CharField(default='tiltbridge', help_text="mDNS ID used by the TiltBridge to identify itself both on your network and to Fermentrack. NOTE - Prefix only - do not include '.local'", max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
