# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0003_auto_20171105_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gravitysensor',
            name='readings_to_average',
        ),
        migrations.RemoveField(
            model_name='gravitysensor',
            name='use_averaged_readings',
        ),
    ]
