# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0003_ispindel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispindelgravitycalibrationpoint',
            name='angle',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Angle (Measured by Device)'),
        ),
    ]
