# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-29 20:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0003_tiltbridge_mdns_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiltbridge',
            name='mdns_id',
            field=models.CharField(help_text="mDNS ID used by the TiltBridge to identify itself both on your network and to Fermentrack. NOTE - Prefix only - do not include '.local'", max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='tiltconfiguration',
            name='tiltbridge',
            field=models.ForeignKey(blank=True, default=None, help_text='TiltBridge device to use (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.TiltBridge'),
        ),
    ]
