# Generated by Django 3.2.12 on 2022-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0004_mdns_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravitysensor',
            name='log_gravity',
            field=models.BooleanField(default=True, help_text='For sensors (such as Brew Bubbles) that primarily log things other than gravity do we want to log the (estimated) gravity readings they make available?'),
        ),
        migrations.AddField(
            model_name='gravitysensor',
            name='log_temp',
            field=models.BooleanField(default=True, help_text='Although most gravity sensors provide temperature readings,we may not always want to log them. Set this false toignore them.'),
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='sensor_type',
            field=models.CharField(choices=[('tilt', 'Tilt Hydrometer'), ('ispindel', 'iSpindel'), ('brewbubbles', 'brewbubbles'), ('plaato', 'plaato'), ('manual', 'Manual')], default='manual', help_text='Type of gravity sensor used', max_length=14),
        ),
    ]
