# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0004_BrewersFriend_Support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravitysensor',
            name='active_log',
            field=models.ForeignKey(blank=True, default=None, help_text='The currently active log of readings', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.GravityLog'),
        ),
    ]
