# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0005_ispindel_float_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiltBridge',
            fields=[
                ('name', models.CharField(help_text='Name to identify this TiltBridge', max_length=64)),
                ('api_key', models.CharField(help_text="API key (a.k.a 'token') provided by the TiltBridge to identify/validate itself when it connects to the Raspberry Pi", max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='connection_type',
            field=models.CharField(choices=[('Bluetooth', 'Bluetooth'), ('Bridge', 'TiltBridge')], default='Bluetooth', help_text='How should Fermentrack connect to this Tilt?', max_length=32),
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='tiltbridge',
            field=models.ForeignKey(default=None, help_text='TiltBridge device to use (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.TiltBridge'),
        ),
    ]
