# Generated by Django 3.2.12 on 2022-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0005_brewbubbles_prep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gravitysensor',
            name='status',
            field=models.CharField(choices=[('active', 'Active, Managed by Fermentrack'), ('unmanaged', 'Active, NOT managed by Fermentrack'), ('disabled', 'Explicitly disabled, cannot be launched'), ('updating', 'Disabled, pending an update')], default='active', help_text='Status of the gravity sensor (used by scripts that interact with it)', max_length=15),
        ),
    ]
