# Generated by Django 3.2.12 on 2023-06-17 19:07

from django.db import migrations, models
import uuid

from gravity.models import GravityLog, GravitySensor, IspindelConfiguration, IspindelGravityCalibrationPoint, \
    TiltBridge, TiltConfiguration, TiltGravityCalibrationPoint, TiltTempCalibrationPoint


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0006_alter_gravitysensor_status'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in GravityLog.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in GravitySensor.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in IspindelConfiguration.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in IspindelGravityCalibrationPoint.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in TiltBridge.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in TiltConfiguration.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in TiltGravityCalibrationPoint.objects.all():
            row.uuid = uuid.uuid4()
            row.save()
        for row in TiltTempCalibrationPoint.objects.all():
            row.uuid = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='gravitylog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='gravitysensor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='ispindelconfiguration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='ispindelgravitycalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='tiltbridge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='tiltgravitycalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.AddField(
            model_name='tilttempcalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Universally unique identifier for this object'),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='gravitylog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='gravitysensor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='ispindelconfiguration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='ispindelgravitycalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='tiltbridge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='tiltconfiguration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='tiltgravitycalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
        migrations.AlterField(
            model_name='tilttempcalibrationpoint',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False,
                                   help_text='Universally unique identifier for this object', unique=True),
        ),
    ]
