# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0006_auto_20180429_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiltbridge',
            options={'verbose_name': 'TiltBridge', 'verbose_name_plural': 'TiltBridges'},
        ),
        migrations.RemoveField(
            model_name='tiltconfiguration',
            name='average_period_secs',
        ),
        migrations.RemoveField(
            model_name='tiltconfiguration',
            name='bluetooth_device_id',
        ),
        migrations.RemoveField(
            model_name='tiltconfiguration',
            name='median_window_vals',
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='grav_constant_term',
            field=models.FloatField(default=0.0, help_text='The constant term in the gravity calibration equation'),
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='grav_first_degree_coefficient',
            field=models.FloatField(default=1.0, help_text='The first degree coefficient in the gravity calibration equation'),
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='grav_second_degree_coefficient',
            field=models.FloatField(default=0.0, help_text='The second degree coefficient in the gravity calibration equation'),
        ),
        migrations.AddField(
            model_name='tiltconfiguration',
            name='smoothing_window_vals',
            field=models.IntegerField(default=70, help_text='Number of readings to include in the smoothing window.'),
        ),
        migrations.AlterField(
            model_name='tiltconfiguration',
            name='polling_frequency',
            field=models.IntegerField(default=15, help_text='How frequently Fermentrack should update the temp/gravity reading'),
        ),
    ]
