# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0007_tilt_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiltconfiguration',
            name='coefficients_up_to_date',
            field=models.BooleanField(default=True, help_text='Have the calibration points changed since the coefficient calculator was run?'),
        ),
    ]
