# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0008_tiltconfiguration_coefficients_up_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiltgravitycalibrationpoint',
            name='orig_value',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5,
                                      verbose_name='Actual (Correct) Gravity value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiltgravitycalibrationpoint',
            name='actual_value',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5,
                                      verbose_name='Tilt Measured Gravity Value'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='tiltgravitycalibrationpoint',
            old_name='actual_value',
            new_name='tilt_measured_gravity',
        ),
        migrations.RenameField(
            model_name='tiltgravitycalibrationpoint',
            old_name='orig_value',
            new_name='actual_gravity',
        ),

    ]
