#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DOCKER_CONTAINER_VERSION="2"

python /app/manage.py collectstatic --noinput
# TODO - Determine if I really want this here
python /app/manage.py migrate --noinput

/usr/bin/supervisord
